version: "3"

services:

  gnbt:
    build: .
    container_name: gnbt
    volumes:
      - /opt/docker/gnbt/config:/config
    ports:
      - 86:8080
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
